BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    #Part 3 & 9
    Button:
        text: 'Clear'
        on_press: app.handle_clear()
    #Part 8
    TextInput:
        id: input_name
        text: ''
    #Part 3
    Button:
        text: 'Greet'
        #Part 4
        on_press: app.handle_greet()
    #Part 1
    Label:
        #Part 6
        id: output_label
        text: "Enter your name"
        #Part 2
        color: (1, 1, 0, 1)